name: Unit Tests

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore dependencies
        run: dotnet restore OmegaFY.Chat.API.sln

      - name: Run unit tests
        run: dotnet test test/OmegaFY.Chat.API.Tests.Unit/OmegaFY.Chat.API.Tests.Unit.csproj --no-restore --verbosity normal

      - name: Create SQLite database
        run: |
          sqlite3 OmegaFYChat.db < "src/OmegaFY.Chat.API.Data.EF/Scripts/001 - Initial_Identity_Tables.sql"
          sqlite3 OmegaFYChat.db < "src/OmegaFY.Chat.API.Data.EF/Scripts/002 - Initial_Domain_Tables.sql"

      - name: Run integration tests
        run: dotnet test test/OmegaFY.Chat.API.Tests.Integration/OmegaFY.Chat.API.Tests.Integration.csproj --no-restore --verbosity normal
